# -*- coding: utf-8 -*-
"""diabetes .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hlSNiu6CBdqH2AdXB128yJYe0HW8H_Rs
"""

import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
from google.colab import drive

from google.colab import drive
drive.mount('/content/drive')

data = pd.read_csv('Heart_Disease_Prediction.csv')

print(data.columns)
X=data.drop('Heart Disease',axis=1)
y=data['Heart Disease']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

scalar = StandardScaler()
X_train_scaled= scalar.fit_transform(X_train)
X_test_scaled= scalar.transform(X_test)

#knn
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix # Import confusion_matrix
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)

Y_pred = knn.predict(X_test)

print("Accuracy:", accuracy_score(y_test, Y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, Y_pred))

#Logistic Regression (liblinear solver)
from sklearn.metrics import classification_report, accuracy_score
log_reg_lib = LogisticRegression(solver="liblinear")
log_reg_lib.fit(X_train, y_train)

y_pred_lib = log_reg_lib.predict(X_test)

print("Accuracy:",
      accuracy_score(y_test, y_pred_lib))
print(classification_report(y_test, y_pred_lib))

#Logistic Regression (lbfgs solver)
log_reg_lbfgs = LogisticRegression(solver="lbfgs", max_iter=1000)
log_reg_lbfgs.fit(X_train, y_train)

y_pred_lbfgs = log_reg_lbfgs.predict(X_test)

print("Logistic Regression (lbfgs) Accuracy:",
      accuracy_score(y_test, y_pred_lbfgs))
print(classification_report(y_test, y_pred_lbfgs))